parameters:
  command.configuration:
    manticore_connection:
      host: "%manticore_migrations.manticore_host%"
      port: "%manticore_migrations.manticore_port%"

    connection:
      driver: "%manticore_migrations.database_driver%"
      host: "%manticore_migrations.database_host%"
      port: "%manticore_migrations.database_port%"
      database: "%manticore_migrations.database_name%"
      user: "%manticore_migrations.database_user%"
      password: "%manticore_migrations.database_password%"
      # if "dsn" key is added, create connection instead of taking previous parameters
      dsn: "%manticore_migrations.database_dsn%"

    migration_table: "%manticore_migrations.database_migration_table%"
    table_prefix: "%manticore_migrations.database_table_prefix%"
    migrations_path: "%manticore_migrations.migrations_path%"


services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  SiroDiaz\ManticoreMigration\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'

  SiroDiaz\ManticoreMigration\Command\AbstractCommand:
    arguments: ['%command.configuration.connection%']
    tags: [ 'console.command' ]


