parameters:
  command.configuration:
    manticore_connection:
      host: "%manticore_migrations.manticore_host%"
      port: "%manticore_migrations.manticore_port%"

    connections: "%manticore_migrations.database_connections%"
    connection: "%manticore_migrations.connection%"

    migration_table: "%manticore_migrations.database_migration_table%"
    table_prefix: "%manticore_migrations.database_table_prefix%"
    migrations_path: "%manticore_migrations.migrations_path%"


services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  SiroDiaz\ManticoreMigration\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'

  SiroDiaz\ManticoreMigration\Command\AbstractCommand:
    arguments:
      $configuration: '%command.configuration%'
    tags: [ 'console.command' ]

  SiroDiaz\ManticoreMigration\Command\FreshCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand

  SiroDiaz\ManticoreMigration\Command\ListMigratedCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand

  SiroDiaz\ManticoreMigration\Command\ListPendingCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand

  SiroDiaz\ManticoreMigration\Command\MakeMigrationCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand

  SiroDiaz\ManticoreMigration\Command\MigrateCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand

  SiroDiaz\ManticoreMigration\Command\RollbackCommand:
    parent: SiroDiaz\ManticoreMigration\Command\AbstractCommand
